from script import match
from soccer import soccer as s

print("To test the code, I am going to take the 2018 FIFA world Cup Matches and run the match function on them")

match("Russia", "Saudi_Arabia", 1,40)
match("Egypt", "Uruguay", 0,40)
match("Morocco", "Iran", 0,40)
match("Portugal", "Spain", 0.5,40)
match("France", "Australia", 1,40)
match("Argentina", "Iceland", 0.5,40)
match("Peru", "Denmark", 0,40)
match("Croatia", "Nigeria", 1,40)
match("Costa_Rica", "Serbia", 0,40)
match("Germany", "Mexico", 0,40)
match("Brazil", "Switzerland", 0.5,40)
match("Sweden", "South_Korea", 1,40)
match("Belgium", "Panama", 1,40)
match("Tunisia", "England", 0,40)
match("Colombia", "Japan", 0,40)
match("Poland", "Senegal", 0,40)
match("Russia", "Egypt", 1,40)
match("Portugal", "Morocco", 1,40)
match("Uruguay", "Saudi_Arabia", 1,40)
match("Iran", "Spain", 0,40)
match("Denmark", "Australia", 0.5,40)
match("France", "Peru", 1,40)
match("Argentina", "Croatia", 0,40)
match("Brazil", "Costa_Rica", 1,40)
match("Nigeria", "Iceland", 1,40)
match("Serbia", "Switzerland", 0,40)
match("Belgium", "Tunisia", 1,40)
match("South_Korea", "Mexico", 0,40)
match("Germany", "Sweden", 1,40)
match("England", "Panama", 1,40)
match("Japan", "Senegal", 0.5,40)
match("Poland", "Colombia", 0,40)
match("Saudi_Arabia", "Egypt", 1,40)
match("Uruguay", "Russia", 1,40)
match("Iran", "Portugal", 0.5,40)
match("Spain", "Morocco", 0.5,40)
match("Australia", "Peru", 0,40)
match("Denmark", "France", 0.5,40)
match("Nigeria", "Argentina", 0,40)
match("Iceland", "Croatia",0,40)
match("Mexico", "Sweden", 0,40)
match("South_Korea", "Germany", 1,40)
match("Switzerland", "Costa_Rica", 0.5,40)
match("Serbia", "Brazil", 0,40)
match("Senegal", "Colombia", 0,40)
match("Japan", "Poland", 0,40)
match("England", "Belgium", 0,40)
match("Panama", "Tunisia", 0,40)
match("France", "Argentina", 1,40)
match("Uruguay", "Portugal", 1,40)
match("Spain", "Russia", 0,40)
match("Croatia", "Denmark", 1,40)
match("Brazil", "Mexico", 1,40)
match("Belgium", "Japan", 1,40)
match("Sweden", "Switzerland", 1,40)
match("Colombia", "England", 0,40)
match("Uruguay", "France", 0,40)
match("Brazil", "Belgium", 0,40)
match("Sweden", "England", 0,40)
match("Russia", "Croatia", 0,40)
match("France", "Belgium", 1,40)
match("Croatia", "England", 1,40)
match("Belgium", "England", 1,40)
match("France", "Croatia", 1,60)

for key, val in s.items():
  print(key, " = ", round(val, 0))